targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          - lib/features/**/providers/*.dart
          - lib/core/providers/*.dart
      json_serializable:
        generate_for:
          - lib/features/**/domain/*.dart
          - lib/core/models/*.dart
        options:
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
