// ═══════════════════════════════════════════════════════════════════════════════
// ⚠️  ARCHITECTURE REFERENCE — NOT COMPILED, NOT WIRED INTO THE APP  ⚠️
// ─────────────────────────────────────────────────────────────────────────────
// This file was MOVED here from lib/features/staff_approval/domain/ as part of the Sprint 1
// scaffold cleanup (Phase 5+). It is preserved as a DESIGN REFERENCE for a
// future typed-model migration, but it is NOT included in the Flutter build
// (this directory is outside `lib/`).
//
// Before relying on this as the design source for a migration, verify field
// shapes match what the live service actually writes to Firestore. See
// download/scaffold-investigation-report.md for full context.
// ═══════════════════════════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════════════════════════
// KLASIVO — Staff Application Model
//
// Mirrors the `staff_applications` Firestore collection.
// Each document represents a staff onboarding application with full
// lifecycle tracking: identity, approval state machine, scope assignment,
// review trail, and archival support.
//
// Key design decisions:
//   - Source of truth for approval status (NOT mirrored on users doc)
//   - Users doc only stores `applicationId` pointer
//   - All state transitions enforced server-side via Firestore transactions
//   - Version field provides idempotency protection against double-clicks
//   - invitedEmailNormalized prevents case-sensitivity invitation bugs
//   - previousApplicationId links reapplication chains
//   - archivedAt/archivedBy enable soft deletion for long-term data hygiene
// ═══════════════════════════════════════════════════════════════════════════════

import 'package:cloud_firestore/cloud_firestore.dart';

import 'staff_approval_status.dart';
import 'staff_type.dart';

/// The source of the staff application.
///
/// - [selfRegistration]: The staff member registered themselves.
/// - [invitation]: An owner/admin invited the staff member.
enum StaffApplicationSource {
  selfRegistration('self_registration'),
  invitation('invitation');

  const StaffApplicationSource(this.value);

  final String value;

  static StaffApplicationSource fromString(String? value) {
    return StaffApplicationSource.values.firstWhere(
      (e) => e.value == value,
      orElse: () => StaffApplicationSource.selfRegistration,
    );
  }
}

/// A staff onboarding application.
///
/// This is the central document for the staff approval workflow.
/// It tracks the full lifecycle from application through approval,
/// rejection, revocation, and archival.
///
/// Firestore collection: `staff_applications`
class StaffApplication {
  // ─── Identity ──────────────────────────────────────────────────────────────

  /// Document ID (auto-generated by Firestore).
  final String id;

  /// Firebase Auth UID of the applicant.
  /// Null until the teacher registers or accepts an invitation.
  final String? userId;

  /// Applicant's email address (as entered or provided by inviter).
  final String email;

  /// Applicant's email in lowercase, for case-insensitive matching.
  /// Example: 'Teacher@School.com' → 'teacher@school.com'
  final String invitedEmailNormalized;

  /// Applicant's display name.
  final String? fullName;

  /// Applicant's phone number.
  final String? phoneNumber;

  /// Applicant's profile photo URL.
  final String? photoUrl;

  // ─── Organization ──────────────────────────────────────────────────────────

  /// The organization this application belongs to.
  final String organizationId;

  // ─── Staff Type ────────────────────────────────────────────────────────────

  /// The type of staff being onboarded (teacher, assistant_teacher, counselor).
  final StaffType staffType;

  // ─── Approval State Machine ────────────────────────────────────────────────

  /// Current approval status.
  final StaffApprovalStatus status;

  /// How this application was initiated.
  final StaffApplicationSource source;

  // ─── Invitation-Specific (Flow C) ──────────────────────────────────────────

  /// Reference to the invite_codes document (if invitation flow).
  final String? inviteCodeId;

  /// UID of the owner/admin who sent the invitation.
  /// Resolve name from users collection, do NOT store name here.
  final String? invitedBy;

  /// When the invitation was sent.
  final DateTime? invitedAt;

  /// When the invitation expires.
  final DateTime? expiresAt;

  // ─── Review ────────────────────────────────────────────────────────────────

  /// UID of the owner/admin who reviewed this application.
  /// Resolve name from users collection, do NOT store name here.
  final String? reviewedBy;

  /// When the application was reviewed.
  final DateTime? reviewedAt;

  /// General notes left by the reviewer for any action (approve, reject, etc.).
  /// Examples: 'Approved after credential review', 'Missing teaching certification'.
  final String? reviewNotes;

  // ─── Revocation ────────────────────────────────────────────────────────────

  /// UID of the owner/admin who revoked access.
  final String? revokedBy;

  /// When the access was revoked.
  final DateTime? revokedAt;

  // ─── Reapplication Chain ───────────────────────────────────────────────────

  /// Reference to the previous application if this is a reapplication.
  /// Enables history chain: Application A (rejected) → Application B (approved).
  final String? previousApplicationId;

  // ─── Scope Assignment (set on approval) ────────────────────────────────────

  /// The RBAC role assigned upon approval.
  /// Defaults to staffType.defaultRole but can be overridden by reviewer.
  final String assignedRole;

  /// Campus IDs assigned to this staff member.
  final List<String> assignedCampusIds;

  /// Stage IDs assigned to this staff member.
  final List<String> assignedStageIds;

  /// Class IDs assigned to this staff member.
  final List<String> assignedClassIds;

  /// Subject IDs assigned to this staff member.
  final List<String> assignedSubjectIds;

  // ─── Metadata ──────────────────────────────────────────────────────────────

  /// Optional note from the applicant explaining their application.
  final String? applicationNote;

  /// Credentials, subjects, or qualifications claimed by the applicant.
  final String? qualifications;

  // ─── Soft Deletion / Archival ──────────────────────────────────────────────

  /// When this application was archived (soft delete).
  /// Archived applications remain in Firestore for audit history
  /// but are excluded from active queries.
  final DateTime? archivedAt;

  /// UID of the user who archived this application.
  final String? archivedBy;

  // ─── Idempotency Protection ────────────────────────────────────────────────

  /// Monotonically increasing version number.
  /// Incremented on every state transition within a Firestore transaction.
  /// Prevents double-click race conditions:
  ///   - Owner clicks Approve twice
  ///   - Two Cloud Function executions race
  ///   - Transaction checks version == expectedVersion before updating
  ///   - Second execution sees version mismatch → rejects
  final int version;

  // ─── Timestamps ────────────────────────────────────────────────────────────

  /// When this application was created.
  final DateTime? createdAt;

  /// When this application was last updated.
  final DateTime? updatedAt;

  // ═══════════════════════════════════════════════════════════════════════════
  // Constructor
  // ═══════════════════════════════════════════════════════════════════════════

  const StaffApplication({
    required this.id,
    this.userId,
    required this.email,
    required this.invitedEmailNormalized,
    this.fullName,
    this.phoneNumber,
    this.photoUrl,
    required this.organizationId,
    required this.staffType,
    required this.status,
    required this.source,
    this.inviteCodeId,
    this.invitedBy,
    this.invitedAt,
    this.expiresAt,
    this.reviewedBy,
    this.reviewedAt,
    this.reviewNotes,
    this.revokedBy,
    this.revokedAt,
    this.previousApplicationId,
    this.assignedRole = 'teacher',
    this.assignedCampusIds = const [],
    this.assignedStageIds = const [],
    this.assignedClassIds = const [],
    this.assignedSubjectIds = const [],
    this.applicationNote,
    this.qualifications,
    this.archivedAt,
    this.archivedBy,
    this.version = 1,
    this.createdAt,
    this.updatedAt,
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Firestore Serialization
  // ═══════════════════════════════════════════════════════════════════════════

  /// Construct from a Firestore document snapshot.
  factory StaffApplication.fromFirestore(
    DocumentSnapshot<Map<String, dynamic>> doc,
  ) {
    final data = doc.data() ?? {};
    return StaffApplication(
      id: doc.id,
      userId: data['userId'] as String?,
      email: data['email'] as String? ?? '',
      invitedEmailNormalized:
          data['invitedEmailNormalized'] as String? ?? '',
      fullName: data['fullName'] as String?,
      phoneNumber: data['phoneNumber'] as String?,
      photoUrl: data['photoUrl'] as String?,
      organizationId: data['organizationId'] as String? ?? '',
      staffType: StaffType.fromString(data['staffType'] as String?),
      status: StaffApprovalStatus.fromString(data['status'] as String?),
      source: StaffApplicationSource.fromString(data['source'] as String?),
      inviteCodeId: data['inviteCodeId'] as String?,
      invitedBy: data['invitedBy'] as String?,
      invitedAt: _timestampToDateTime(data['invitedAt'] as Timestamp?),
      expiresAt: _timestampToDateTime(data['expiresAt'] as Timestamp?),
      reviewedBy: data['reviewedBy'] as String?,
      reviewedAt: _timestampToDateTime(data['reviewedAt'] as Timestamp?),
      reviewNotes: data['reviewNotes'] as String?,
      revokedBy: data['revokedBy'] as String?,
      revokedAt: _timestampToDateTime(data['revokedAt'] as Timestamp?),
      previousApplicationId: data['previousApplicationId'] as String?,
      assignedRole: data['assignedRole'] as String? ?? 'teacher',
      assignedCampusIds:
          List<String>.from(data['assignedCampusIds'] as List? ?? []),
      assignedStageIds:
          List<String>.from(data['assignedStageIds'] as List? ?? []),
      assignedClassIds:
          List<String>.from(data['assignedClassIds'] as List? ?? []),
      assignedSubjectIds:
          List<String>.from(data['assignedSubjectIds'] as List? ?? []),
      applicationNote: data['applicationNote'] as String?,
      qualifications: data['qualifications'] as String?,
      archivedAt: _timestampToDateTime(data['archivedAt'] as Timestamp?),
      archivedBy: data['archivedBy'] as String?,
      version: data['version'] as int? ?? 1,
      createdAt: _timestampToDateTime(data['createdAt'] as Timestamp?),
      updatedAt: _timestampToDateTime(data['updatedAt'] as Timestamp?),
    );
  }

  /// Construct from a raw Firestore map (without document snapshot).
  /// Useful when data is already extracted from a snapshot.
  factory StaffApplication.fromMap(
    Map<String, dynamic> data,
    String id,
  ) {
    return StaffApplication(
      id: id,
      userId: data['userId'] as String?,
      email: data['email'] as String? ?? '',
      invitedEmailNormalized:
          data['invitedEmailNormalized'] as String? ?? '',
      fullName: data['fullName'] as String?,
      phoneNumber: data['phoneNumber'] as String?,
      photoUrl: data['photoUrl'] as String?,
      organizationId: data['organizationId'] as String? ?? '',
      staffType: StaffType.fromString(data['staffType'] as String?),
      status: StaffApprovalStatus.fromString(data['status'] as String?),
      source: StaffApplicationSource.fromString(data['source'] as String?),
      inviteCodeId: data['inviteCodeId'] as String?,
      invitedBy: data['invitedBy'] as String?,
      invitedAt: _timestampToDateTime(data['invitedAt'] as Timestamp?),
      expiresAt: _timestampToDateTime(data['expiresAt'] as Timestamp?),
      reviewedBy: data['reviewedBy'] as String?,
      reviewedAt: _timestampToDateTime(data['reviewedAt'] as Timestamp?),
      reviewNotes: data['reviewNotes'] as String?,
      revokedBy: data['revokedBy'] as String?,
      revokedAt: _timestampToDateTime(data['revokedAt'] as Timestamp?),
      previousApplicationId: data['previousApplicationId'] as String?,
      assignedRole: data['assignedRole'] as String? ?? 'teacher',
      assignedCampusIds:
          List<String>.from(data['assignedCampusIds'] as List? ?? []),
      assignedStageIds:
          List<String>.from(data['assignedStageIds'] as List? ?? []),
      assignedClassIds:
          List<String>.from(data['assignedClassIds'] as List? ?? []),
      assignedSubjectIds:
          List<String>.from(data['assignedSubjectIds'] as List? ?? []),
      applicationNote: data['applicationNote'] as String?,
      qualifications: data['qualifications'] as String?,
      archivedAt: _timestampToDateTime(data['archivedAt'] as Timestamp?),
      archivedBy: data['archivedBy'] as String?,
      version: data['version'] as int? ?? 1,
      createdAt: _timestampToDateTime(data['createdAt'] as Timestamp?),
      updatedAt: _timestampToDateTime(data['updatedAt'] as Timestamp?),
    );
  }

  /// Convert to a Firestore-compatible map.
  Map<String, dynamic> toFirestore() {
    return {
      'userId': userId,
      'email': email,
      'invitedEmailNormalized': invitedEmailNormalized,
      'fullName': fullName,
      'phoneNumber': phoneNumber,
      'photoUrl': photoUrl,
      'organizationId': organizationId,
      'staffType': staffType.value,
      'status': status.value,
      'source': source.value,
      'inviteCodeId': inviteCodeId,
      'invitedBy': invitedBy,
      'invitedAt': invitedAt != null ? Timestamp.fromDate(invitedAt!) : null,
      'expiresAt':
          expiresAt != null ? Timestamp.fromDate(expiresAt!) : null,
      'reviewedBy': reviewedBy,
      'reviewedAt':
          reviewedAt != null ? Timestamp.fromDate(reviewedAt!) : null,
      'reviewNotes': reviewNotes,
      'revokedBy': revokedBy,
      'revokedAt':
          revokedAt != null ? Timestamp.fromDate(revokedAt!) : null,
      'previousApplicationId': previousApplicationId,
      'assignedRole': assignedRole,
      'assignedCampusIds': assignedCampusIds,
      'assignedStageIds': assignedStageIds,
      'assignedClassIds': assignedClassIds,
      'assignedSubjectIds': assignedSubjectIds,
      'applicationNote': applicationNote,
      'qualifications': qualifications,
      'archivedAt':
          archivedAt != null ? Timestamp.fromDate(archivedAt!) : null,
      'archivedBy': archivedBy,
      'version': version,
      'createdAt':
          createdAt != null ? Timestamp.fromDate(createdAt!) : null,
      'updatedAt':
          updatedAt != null ? Timestamp.fromDate(updatedAt!) : null,
    };
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // copyWith
  // ═══════════════════════════════════════════════════════════════════════════

  /// Create a copy with updated fields.
  /// Does NOT auto-increment version; that must be done in the
  /// Cloud Function within a transaction.
  StaffApplication copyWith({
    String? userId,
    String? email,
    String? invitedEmailNormalized,
    String? fullName,
    String? phoneNumber,
    String? photoUrl,
    String? organizationId,
    StaffType? staffType,
    StaffApprovalStatus? status,
    StaffApplicationSource? source,
    String? inviteCodeId,
    String? invitedBy,
    DateTime? invitedAt,
    DateTime? expiresAt,
    String? reviewedBy,
    DateTime? reviewedAt,
    String? reviewNotes,
    String? revokedBy,
    DateTime? revokedAt,
    String? previousApplicationId,
    String? assignedRole,
    List<String>? assignedCampusIds,
    List<String>? assignedStageIds,
    List<String>? assignedClassIds,
    List<String>? assignedSubjectIds,
    String? applicationNote,
    String? qualifications,
    DateTime? archivedAt,
    String? archivedBy,
    int? version,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return StaffApplication(
      id: id,
      userId: userId ?? this.userId,
      email: email ?? this.email,
      invitedEmailNormalized:
          invitedEmailNormalized ?? this.invitedEmailNormalized,
      fullName: fullName ?? this.fullName,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      photoUrl: photoUrl ?? this.photoUrl,
      organizationId: organizationId ?? this.organizationId,
      staffType: staffType ?? this.staffType,
      status: status ?? this.status,
      source: source ?? this.source,
      inviteCodeId: inviteCodeId ?? this.inviteCodeId,
      invitedBy: invitedBy ?? this.invitedBy,
      invitedAt: invitedAt ?? this.invitedAt,
      expiresAt: expiresAt ?? this.expiresAt,
      reviewedBy: reviewedBy ?? this.reviewedBy,
      reviewedAt: reviewedAt ?? this.reviewedAt,
      reviewNotes: reviewNotes ?? this.reviewNotes,
      revokedBy: revokedBy ?? this.revokedBy,
      revokedAt: revokedAt ?? this.revokedAt,
      previousApplicationId:
          previousApplicationId ?? this.previousApplicationId,
      assignedRole: assignedRole ?? this.assignedRole,
      assignedCampusIds: assignedCampusIds ?? this.assignedCampusIds,
      assignedStageIds: assignedStageIds ?? this.assignedStageIds,
      assignedClassIds: assignedClassIds ?? this.assignedClassIds,
      assignedSubjectIds: assignedSubjectIds ?? this.assignedSubjectIds,
      applicationNote: applicationNote ?? this.applicationNote,
      qualifications: qualifications ?? this.qualifications,
      archivedAt: archivedAt ?? this.archivedAt,
      archivedBy: archivedBy ?? this.archivedBy,
      version: version ?? this.version,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Convenience Getters
  // ═══════════════════════════════════════════════════════════════════════════

  /// Whether this application is for an invitation flow.
  bool get isInvitation => source == StaffApplicationSource.invitation;

  /// Whether this application is for a self-registration flow.
  bool get isSelfRegistration =>
      source == StaffApplicationSource.selfRegistration;

  /// Whether this application has been archived (soft deleted).
  bool get isArchived => archivedAt != null;

  /// Whether this application has been reviewed (approved or rejected).
  bool get hasBeenReviewed =>
      status == StaffApprovalStatus.approved ||
      status == StaffApprovalStatus.rejected;

  /// Whether this is a reapplication (has a previous application).
  bool get isReapplication => previousApplicationId != null;

  /// Whether this application has scope assignments set.
  bool get hasScopeAssignment =>
      assignedCampusIds.isNotEmpty ||
      assignedStageIds.isNotEmpty ||
      assignedClassIds.isNotEmpty ||
      assignedSubjectIds.isNotEmpty;

  /// Whether the invitation has expired.
  bool get isInvitationExpired =>
      status == StaffApprovalStatus.invited &&
      expiresAt != null &&
      expiresAt!.isBefore(DateTime.now());

  // ═══════════════════════════════════════════════════════════════════════════
  // Helpers
  // ═══════════════════════════════════════════════════════════════════════════

  /// Convert a Firestore Timestamp to DateTime, returning null if null.
  static DateTime? _timestampToDateTime(Timestamp? timestamp) {
    return timestamp?.toDate();
  }

  @override
  String toString() =>
      'StaffApplication(id: $id, email: $email, status: ${status.value}, '
      'staffType: ${staffType.value}, orgId: $organizationId, version: $version)';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StaffApplication &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          version == other.version &&
          status == other.status;

  @override
  int get hashCode => id.hashCode ^ version.hashCode ^ status.hashCode;
}
